### ISSUE TITLE
pgjwt

### ISSUE THREAD

**Issue by ahopkins** [priyank-purohit/PostGUI#21]
Which version of the extension do you need for this? How can I go about installing it.

**Comment by priyank-purohit** [comment]
Hey @ahopkins ,

Does this work for you: https://github.com/priyank-purohit/PostGUI/blob/master/scripts/Authentication.sql#L8-L11 ?

Perhaps this would help from the PostgREST discussions: https://gitter.im/begriffs/postgrest?at=5da9e3c678e4974ace7b48f1

And https://www.google.com/search?q=how+to+install+pgjwt+postgrest would be the general search for this.

**Comment by ahopkins** [comment]
Thanks. I was trying to install inside a docker container and ultimately decided to go another route.
