### ISSUE TITLE
Trying to npm start PostGUI on Windows 10 fails

### ISSUE THREAD

**Issue by chocobloc** [priyank-purohit/PostGUI#7]
I've downloaded a fresh .zip file and installed it according to the documentation. PostgREST is running locally on port 3020. A npm start will result in the following .log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle postgui@1.2.0~prestart: postgui@1.2.0
6 info lifecycle postgui@1.2.0~start: postgui@1.2.0
7 verbose lifecycle postgui@1.2.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle postgui@1.2.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;c:\sources\post-gui\node_modules\.bin;C:\Python37\Scripts\;C:\Python37\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\Program Files\PostgreSQL\10\bin\;C:\Users\Heinz-Peter Scharf\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Java\jdk1.8.0_144;%JAVA_HOME\bin;C:\bin\wildfly-10.1.0.Final;%JBOSS_HOME\bin;C:\Program Files\apache-maven-3.6.1\bin;C:\Users\Heinz-Peter Scharf\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Heinz-Peter Scharf\AppData\Roaming\npm
9 verbose lifecycle postgui@1.2.0~start: CWD: c:\sources\post-gui
10 silly lifecycle postgui@1.2.0~start: Args: [ '/d /s /c', 'PORT=8771 react-scripts start' ]
11 silly lifecycle postgui@1.2.0~start: Returned: code: 1  signal: null
12 info lifecycle postgui@1.2.0~start: Failed to exec start script
13 verbose stack Error: postgui@1.2.0 start: `PORT=8771 react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid postgui@1.2.0
15 verbose cwd c:\sources\post-gui
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error postgui@1.2.0 start: `PORT=8771 react-scripts start`
22 error Exit status 1
23 error Failed at the postgui@1.2.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Could you please help to clarify why PostGUI doesn't start properly.

Thanks in advance!

**Comment by priyank-purohit** [comment]
Sorry, I never got an email about this issue!

I haven't encountered this issue -- but a [quick google search](https://www.google.com/search?q=20+error+code+ELIFECYCLE+21+error+errno+1&oq=20+error+code+ELIFECYCLE+21+error+errno+1) suggests this may be related to [node modules installation](https://stackoverflow.com/questions/42308879/npm-err-code-elifecycle).
