### ISSUE TITLE
Readme images missing

### ISSUE THREAD

**Issue by taitems** [priyank-purohit/PostGUI#9]
Hey there, trying to learn more but all your screenshots are missing/broken.

**Comment by priyank-purohit** [comment]
Hey @taitems they're loading fine for me, perhaps an internet connection issue on your machine? May be try a hard refresh, or you can refer to the source at https://github.com/priyank-purohit/PostGUI/tree/master/docs/images

**Comment by taitems** [comment]
Very strange. I think it's because we recently rolled out some new AV and DNS stuff within our work machines so that's probably corrupting it. Odd.

![image](https://user-images.githubusercontent.com/234593/71637634-f3cbe380-2c9b-11ea-9784-dee5d5f50701.png)

Ha, it won't even let me see my own pasted image above :(
